blank_issues_enabled: false
contact_links:
  - name: 💬 لأي استفسار عام أو مناقشة
    url: https://github.com/ahmedalmnsour/khitab/discussions
    about: إذا كان لديك سؤال عام أو تريد اقتراح فكرة للمشروع، يُرجى فتح مناقشة هنا.